### ISSUE TITLE
Sensitive Info in Code 

### ISSUE THREAD

**Issue by StickeyTape** [sylv1b/cronGuru#1]
Hi Sylvain,

Just stumbled on your code this morning ant noticed something you might want to remove from your code.

https://github.com/sylv1b/cronGuru/blob/414340c6d8e32e3b3d10e4370eb041891732b188/src/calls.js#L250

Cheers mate! Just sharing with you before someone malicious goes and messes with it.

**Comment by sylv1b** [comment]
> Hi Sylvain,
> 
> Just stumbled on your code this morning ant noticed something you might want to remove from your code.
> 
> https://github.com/sylv1b/cronGuru/blob/414340c6d8e32e3b3d10e4370eb041891732b188/src/calls.js#L250
> 
> Cheers mate! Just sharing with you before someone malicious goes and messes with it.

Thank you for sharing. I was certain that I removed it and passed it as environment variables. I'll remove that soon. Until then, I changed my password.

**Comment by StickeyTape** [comment]
Awesome stuff!  
Keep Safe!
